language: bash
os:
  - linux

services:
  - docker

git:
  submodules: false

script:
 - git clone --depth=1 --recurse-submodules --shallow-submodules -j4 https://github.com/valbeat/dotfiles.git ./dotfiles
 - rm -rf dotfiles/.git
 - mv ./dotfiles/.[^\.]* .
 - travis_wait 30 docker build -t valbeat/dotfiles:${TRAVIS_BUILD_NUMBER} .
 # FIXME: `__zplug::job::message::red:3: character not in range`
 - docker run --rm -it valbeat/dotfiles:${TRAVIS_BUILD_NUMBER} zsh -c "source ~/.zshrc || source ~/.zshrc"
 - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
 - docker tag valbeat/dotfiles:${TRAVIS_BUILD_NUMBER} valbeat/dotfiles:latest
 - docker push valbeat/dotfiles:latest
