language: bash
os:
  - linux

services:
  - docker

git:
  submodules: false

before_install:
  - git clone https://github.com/valbeat/dotfiles.git ./dotfiles
  - rm -rf dotfiles/.git
  - mv ./dotfiles/.[^\.]* .
  - docker build -t ${DOCKER_IMAGE}:${TRAVIS_BUILD_NUMBER} .

script:
  # FIXME: `__zplug::job::message::red:3: character not in range`
  - docker run --rm -it ${DOCKER_IMAGE} zsh -c "source ~/.zshrc || source ~/.zshrc"

after_success:
 - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
 - docker tag ${DOCKER_IMAGE}:${TRAVIS_BUILD_NUMBER} ${DOCKER_IMAGE}:latest
 - docker push ${DOCKER_IMAGE}:latest
