name: Build and Push
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clone Dotfiles repo
        run: |
          git clone --depth=1 --recurse-submodules --shallow-submodules -j4 https://github.com/valbeat/dotfiles.git ./dotfiles
          rm -rf ./dotfiles/.git
          mv ./dotfiles/.[^\.]* .
          docker build -t valbeat/dotfiles:${GITHUB_REF} .
          # FIXME: `__zplug::job::message::red:3: character not in range`
          docker run --rm -it valbeat/dotfiles:${GITHUB_REF}  zsh -c "source ~/.zshrc || source ~/.zshrc"
          docker tag valbeat/dotfiles:${GITHUB_REF} valbeat/dotfiles:${GITHUB_REF}
          docker push valbeat/dotfiles:${GITHUB_REF}

