name: Test
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build sandbox image
        run: |
          git clone --depth=1 --recurse-submodules --shallow-submodules -j4 https://github.com/valbeat/dotfiles.git ./dotfiles
          rm -rf ./dotfiles/.git
          rm -rf ./dotfiles/.github
          mv ./dotfiles/.[^\.]* .
          docker build -t valbeat/dotfiles:${{ github.sha }} .

      - name: Run tests
        run: |
          docker run --rm valbeat/dotfiles:${{ github.sha }} zsh -c "source ~/.zshrc"

      - name: Push sandbox image
        run: docker push valbeat/dotfiles:${{ github.sha }}
