name: Test
on:
  push:
    branches: 
    - main
  schedule:
    - cron: '0 * * * *'
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clone dotfiles
        run: |
          git clone --depth=1 --recurse-submodules --shallow-submodules -j4 https://github.com/valbeat/dotfiles.git ./dotfiles
          cd ./dotfiles
          echo $(git rev-parse --short HEAD)
          DOTFILES_HASH=$(git rev-parse --short HEAD)
          echo dotfiles_hash=$DOTFILES_HASH >> $GITHUB_ENV
          cd ..
          rm -rf ./dotfiles/.git
          rm -rf ./dotfiles/.github
          mv ./dotfiles/.[^\.]* .

      - name: Build sandbox image
        run: |
          docker build -t valbeat/dotfiles:${{ env.dotfiles_hash }} .

      - name: Run tests
        run: |
          docker run --rm valbeat/dotfiles:${{ env.dotfiles_hash }}

      - name: Push sandbox image
        run: |
          docker push valbeat/dotfiles:${{ env.dotfiles_hash }}
