name: Test
on:
  push:
    branches: 
    - main
  schedule:
    - cron: '0 * * * *'
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build sandbox image
        run: |
          git clone --depth=1 --recurse-submodules --shallow-submodules -j4 https://github.com/valbeat/dotfiles.git ./dotfiles
          cd ./dotfiles
          COMMIT_HASH=`git rev-parse HEAD`
          echo "commit_hash=$COMMIT_HASH" >> $GITHUB_ENV
          rm -rf .git
          rm -rf .github
          mv ./.[^\.]* ..
          cd ..
          docker build -t valbeat/dotfiles:${{ github.commit_hash }} .

      - name: Run tests
        run: |
          docker run --rm valbeat/dotfiles:${{ github.commit_hash }} zsh -c "source ~/.zshrc"

      - name: Push sandbox image
        run: |
          docker push valbeat/dotfiles:${{ github.commit_hash }}
